// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrYdRyllVGAIsu0RULt-m2aR0m4iuyOA',
    appId: '1:580194319126:web:a9543538c537f3de0c6e37',
    messagingSenderId: '580194319126',
    projectId: 'insurancetech-f69e9',
    authDomain: 'insurancetech-f69e9.firebaseapp.com',
    storageBucket: 'insurancetech-f69e9.appspot.com',
    measurementId: 'G-NLCLFPCNXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnpQbcxrtYM3RWSVQ88MUx_GDBQu7dxY',
    appId: '1:580194319126:android:496474ca7acdba730c6e37',
    messagingSenderId: '580194319126',
    projectId: 'insurancetech-f69e9',
    storageBucket: 'insurancetech-f69e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElwlASNwx4xnyCLPO9rOZ0ZymX6Husxw',
    appId: '1:580194319126:ios:04b4ca74c593ce660c6e37',
    messagingSenderId: '580194319126',
    projectId: 'insurancetech-f69e9',
    storageBucket: 'insurancetech-f69e9.appspot.com',
    iosClientId: '580194319126-jdc37432n9i2ngburn6a3b1tkd66ku4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurancetech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElwlASNwx4xnyCLPO9rOZ0ZymX6Husxw',
    appId: '1:580194319126:ios:04b4ca74c593ce660c6e37',
    messagingSenderId: '580194319126',
    projectId: 'insurancetech-f69e9',
    storageBucket: 'insurancetech-f69e9.appspot.com',
    iosClientId: '580194319126-jdc37432n9i2ngburn6a3b1tkd66ku4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurancetech',
  );
}
