// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOU_myhCnwrc4Zm0zqUwgQ0DX8bPRNirU',
    appId: '1:443531705802:web:aca57a7fdf3c90e7622333',
    messagingSenderId: '443531705802',
    projectId: 'smdinsurancetech',
    authDomain: 'smdinsurancetech.firebaseapp.com',
    databaseURL: 'https://smdinsurancetech-default-rtdb.firebaseio.com',
    storageBucket: 'smdinsurancetech.appspot.com',
    measurementId: 'G-RXDK7GKB5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mJtHcUAefa-layJVU0FPuRCRXX2SzrY',
    appId: '1:443531705802:android:72a7122be2a35563622333',
    messagingSenderId: '443531705802',
    projectId: 'smdinsurancetech',
    databaseURL: 'https://smdinsurancetech-default-rtdb.firebaseio.com',
    storageBucket: 'smdinsurancetech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3YiGZ_ejfUexSzATajI9hGfTMjGFqlU',
    appId: '1:443531705802:ios:fa2bdf0a5b01385e622333',
    messagingSenderId: '443531705802',
    projectId: 'smdinsurancetech',
    databaseURL: 'https://smdinsurancetech-default-rtdb.firebaseio.com',
    storageBucket: 'smdinsurancetech.appspot.com',
    iosClientId: '443531705802-sagpn8hedg2n6eooni73nms7bghirbdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurancetech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3YiGZ_ejfUexSzATajI9hGfTMjGFqlU',
    appId: '1:443531705802:ios:fa2bdf0a5b01385e622333',
    messagingSenderId: '443531705802',
    projectId: 'smdinsurancetech',
    databaseURL: 'https://smdinsurancetech-default-rtdb.firebaseio.com',
    storageBucket: 'smdinsurancetech.appspot.com',
    iosClientId: '443531705802-sagpn8hedg2n6eooni73nms7bghirbdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurancetech',
  );
}
